image: ytchiang/laravel-echo-server-env:release-1.3.9

imagePullPolicy: IfNotPresent

service:
  enabled: true
  type: "ClusterIP"

config:
  authHost: "http://localhost"
  authEndpoint: "/broadcasting/auth"
  database: "redis"
  redisHost: "redis-master"
  redisPort: "6379"
  redisPassword: ""
  redisPasswordSecretName: "redis"
  redisPasswordSecretKey: "redis-password"
  redisDB: "0"
  sqlitePath: ""
  devMode: true
  port: "6001"
  protocol: "http"
  allow_cors: true
  allow_origin: "http://localhost:80"
  allow_methods: "GET, POST"
  allow_headers: "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
  client_key: ""
