apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laravel-echo-server
  labels:
    app: laravel-echo-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: laravel-echo-server
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: laravel-echo-server
        ports:
        - containerPort: 6001
          name: rest-port

        volumeMounts:
          - name: laravel-echo-server-conf
            mountPath: /app/laravel-echo-server.json
            subPath: laravel-echo-server.json
            readOnly: true
      volumes:
        - name: laravel-echo-server-conf
          configMap:
            name: laravel-echo-server-conf
