apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laravel-echo-server
  labels:
    app: laravel-echo-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: laravel-echo-server
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: laravel-echo-server
        ports:
        - containerPort: {{ .Values.config.redisPort}}
          name: rest-port
        env:
        - name: AUTH_HOST
          value: {{ .Values.config.authHost | quote}}
        - name: AUTH_ENDPOINT
          value: {{ .Values.config.authEndpoint | quote}}
        - name: DATABASE
          value: {{ .Values.config.database | quote}}
        - name: REDIS_HOST
          value: {{ .Values.config.redisHost | quote}}
        - name: REDIS_PORT
          value: {{ .Values.config.redisPort | quote}}
{{ if .Values.config.redisPasswordSecretName }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.redisPasswordSecretName | quote}}
              key: {{ .Values.config.redisPasswordSecretKey | quote}}
{{ else }}
        - name: REDIS_PASSWORD
          value: {{ .Values.config.redisPassword | quote}}
{{ end }}
        - name: REDIS_DB
          value: {{ .Values.config.redisDB | quote}}
        - name: SQLITE_PATH
          value: {{ .Values.config.sqlitePath | quote}}
        - name: CLIENT_KEY
          value: {{ .Values.config.client_key | quote}}
        - name: DEV_MODE
          value: {{ .Values.config.devMode | quote}}
#        - name: ECHO_SERVER_HOST
#          value: {{ .Values.config.database }}
        - name: ECHO_SERVER_PORT
          value: {{ .Values.config.port | quote}}
        - name: ECHO_SERVER_PROTOCOL
          value: {{ .Values.config.protocol | quote}}
        - name: ALLOW_CORS
          value: {{ .Values.config.allow_cors | quote}}
        - name: ALLOW_ORIGIN
          value: {{ .Values.config.allow_origin | quote}}
        - name: ALLOW_METHODS
          value: {{ .Values.config.allow_methods | quote}}
        - name: ALLOW_HEADERS
          value: {{ .Values.config.allow_headers | quote}}
