apiVersion: v1
kind: Service
metadata:
  name: laravel-echo-server
  labels:
    app: laravel-echo-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
spec:
  type: {{.Values.service.type}}
  clusterIP: None
  ports:
  - name: laravel-echo-server
    port: 6001
  selector:
    app: laravel-echo-server
